version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    # network_mode: host
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/www:/usr/share/nginx/html
      - ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    # environment:
    #   - NGINX_HOST=your.domain
    #   - NGINX_PORT=80
