version: '2'
services:
  nginx:
    build: ./nginx
    container_name: prometheus-nginx-vts
    restart: always
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx
    ports:
      - 9114:80
    networks:
      - localhost

  promtail:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: prometheus-nginx-exporter
    restart: always
    ports:
      - 9113:9113
    command: 
      - -nginx.scrape-uri=http://host.docker.internal:9114/stub_status
    networks:
      - localhost

networks:
    localhost:
        name: localhost
        external: false
