version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: prometheus-nginx
    restart: always
    # network_mode: host
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx
    ports:
      - 9090:80
    networks:
      - localhost

  promtail:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: prometheus-nginx-exporter
    restart: always
    ports:
      - 9113:9113
    volumes:
      - ./nginx/logs:/var/log
      - ./promtail:/etc/promtail
    command: 
      - -nginx.scrape-uri=http://nginx/stub_status
    networks:
      - localhost

networks:
    localhost:
        name: localhost
        external: false
