version: "3"
services:
  gitlab-service:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "192.168.79.8"
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://192.168.79.8'
          nginx['listen_port'] = 80
          gitlab_rails['gitlab_shell_ssh_port'] = 9022
    ports:
      - "9000:80"
      - "9443:443"
      - "9022:22"
    volumes:
      - "/Users/double/soft/gitlab-data/config:/etc/gitlab"
      - "/Users/double/soft/gitlab-data/logs:/var/log/gitlab"
      - "/Users/double/soft/gitlab-data/data:/var/opt/gitlab"

