version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    restart: always
    # network_mode: host
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx
    ports:
      - 9090:80
    # environment:
    #   - NGINX_HOST=your.domain
    #   - NGINX_PORT=80

  promtail:
    image: grafana/promtail:2.9.2
    ports:
      - 9080:9080
    volumes:
      - ./nginx/logs:/var/log
      - ./promtail:/etc/promtail
    command: -config.file=/etc/promtail/config.yml
    # networks:
    #   - host
