version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--local-infile=0
    volumes:
      - './mariadb_data:/bitnami'
  phabricator:
    image: 'bitnami/phabricator:2020'
    ports:
      - '80:80'
      - '443:443'
      - '222:22'
      - '5555:5555'
    volumes:
      - './phabricator_data:/bitnami'
      - './my_vhost.conf:/opt/bitnami/apache/conf/vhosts/my_vhost.conf'
    environment:
      - PHABRICATOR_HOST=172.16.23.82
      - PHABRICATOR_USERNAME=admin
      - PHABRICATOR_PASSWORD=Abc123456
      - PHABRICATOR_ENABLE_GIT_SSH_REPOSITORY=yes
      - PHABRICATOR_SSH_PORT_NUMBER=5555

    # 可选配置...
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  phabricator_data:
    driver: local